from typing import List, Tuple
import numpy as np
from scipy.integrate import odeint
from scipy import signal as signal


class IntSolverAufgabe4:
    def __init__(self) -> None:
        return None

    def calculate(
        self, x: Tuple[float, float], t: List[float], c: float, d: float, m: float
    ) -> Tuple[float, float]:
        x_1, x_2 = x[0], x[1]

        x_dot = (x_2, -d / m * x_2 - c / m * x_1)
        return x_dot

    def integrate(self, func, start_deflection: float, start_velocity: float, t, *args):
        y_0 = (start_deflection, start_velocity)
        # variabel
        x = odeint(func=func, y0=y_0, t=t, args=args)

        return x


class IntSolverAufgabe1:
    def __init__(self) -> None:
        return None

    # Dauerlauf
    def state_space_settled(self, z, t, d, m, c, omega):
        delta = d / (3 * m)
        omega_0 = np.sqrt(2 * c / (3 * m))
        b0 = 2 / (3 * m)
        [x, x_p] = z  # Zustandsvektor
        z_p = [
            x_p,
            -2 * delta * x_p - omega_0**2 * x + b0 * np.cos(omega * t),
        ]  # Zustands-DGL
        return z_p

    # Hochlauf
    def state_space_accelerated(self, z, t, d, m, c, omega):
        delta = d / (3 * m)
        omega_0 = np.sqrt(2 * c / (3 * m))
        alpha = omega / 100
        b0 = 2 / (3 * m)
        [x, x_p] = z
        z_p = [
            x_p,
            -2 * delta * x_p - omega_0**2 * x + b0 * np.cos(0.5 * alpha * t**2),
        ]
        return z_p

    def integrate(self, func, t, start_deflection, start_velocity, *args):
        print(args)
        z0 = (start_deflection, start_velocity)
        return odeint(func=func, y0=z0, t=t, args=args)[:, 0]


def validate_solution(solution, correct_solution, relative_threshold=0.05):
    """Validates the student's solution against the correct solution.

    This function compares the student's solution with the correct solution at each time step.
    If the difference between the two solutions is within the specified threshold, the solution
    is considered valid.

    Args:
        solution (numpy.ndarray): The solution generated by the student's implementation.
        correct_solution (numpy.ndarray): The solution generated by the correct implementation.
        relative_threshold (float): The allowable difference between the two solutions at any time
            step indicated in percentage (decimal). Defaults to 0.05.

    Returns:
        bool: True if the student's solution is within the threshold of the correct solution,
                False otherwise.
    """
    # check if shape of solutions match
    if solution.shape != correct_solution.shape:
        print("Error: Your solution and the correct solution have different shapes.")
        return False

    # compare the solutions at each time step
    for j in range(len(solution)):
        # avoid division by zero for very small correct_solution values
        if abs(correct_solution[j]) < 1e-10:
            if abs(solution[j] - correct_solution[j]) > 1e-10:
                print(f"Solution mismatch at time step {j}.")
                print(f"Yours: {solution[j]}, Correct: {correct_solution[j]}")
                return False
        else:
            relative_error = abs(
                (solution[j] - correct_solution[j]) / correct_solution[j]
            )
            if relative_error > relative_threshold:
                print(f"Solution mismatch at time step {j}.")
                print(
                    f"Yours: {solution[j]}, Correct: {correct_solution[j]}, Relative Error: {relative_error}"
                )
                return False

    # If all checks pass, the solution is valid
    print("Yor solution is correct!")
    return True
